[workspace]
resolver = "3"
members = ["plux-codegen", "plux-mock"]

[workspace.package]
authors = ["Bleyn"]
license = "MIT"
homepage = "https://github.com/BleynChannel/plux-rs"
repository = "https://github.com/BleynChannel/plux-rs"
edition = "2024"
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*",
]

[package]
name = "plux-rs"
description = "A modular and performant plugin system for Rust applications, enabling secure and stable extension of functionality through external plugins."
version = "1.1.2"
readme = "README.md"
keywords = ["plugin", "modular", "extensibility", "dynamic-loading", "api"]
categories = ["api-bindings", "development-tools"]
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utils
plux-codegen = { path = "./plux-codegen", version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }
thiserror = "2.0"

# Parallel
rayon = "1.11"

# Archive
walkdir = { version = "2.5", optional = true }
zip = { version = "6", optional = true }

[dev-dependencies]
plux-codegen = { path = "./plux-codegen", version = "0.3" }
plux-mock = { path = "./plux-mock", version = "0.1" }
plux-lua-manager = { path = "../managers/plux-lua-manager", version = "0.1" }
semver = { version = "1.0", features = ["serde"] }
toml = "0.9"
gethostname = "1.1"
egui = "0.33"
eframe = "0.33"

[features]
default = ["full"]
full = ["derive", "archive"]
derive = ["dep:plux-codegen"]
archive = ["dep:walkdir", "dep:zip"]
