[package]
name = "plux"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plux-codegen = { path = "codegen", optional = true }
rayon = "1.11"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
walkdir = { version = "2.5", optional = true }
zip = { version = "4.6", optional = true }

[dev-dependencies]
plux-codegen = { path = "codegen" }
plux-lua-manager = { git = "https://github.com/BleynChannel/plux-lua-manager.git", branch = "master" }
semver = { version = "1.0", features = ["serde"] }
toml = "0.9"

[features]
default = ["full"]
full = ["derive", "archive"]
derive = ["dep:plux-codegen"]
archive = ["dep:walkdir", "dep:zip"]
