[package]
name = "plux-mock"
description = ""
version = "0.1.0"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

[dependencies]
plux-rs = { path = "..", version = "1.1", default-features = false, features = ["derive"]}
semver = "1.0"
serde = "1.0"
thiserror = "2.0"
toml = "0.9"
